version: "3.9"

networks:
  camera-net:
    external: true

services:
  mosquitto:
    container_name: camera-mosquitto
    image: camera-mosquitto:latest
    networks:
      - camera-net
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - /opt/camera-app/tls-mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /opt/camera-app/certs:/mosquitto/certs
    restart: unless-stopped

  mediamtx:
    container_name: camera-mediamtx
    image: camera-mediamtx:latest
    networks:
      - camera-net
    ports:
      - "8554:8554"
      - "8888:8888"
      - "8889:8889"
    volumes:
      - /opt/camera-app/mediamtx.yml:/app/mediamtx.yml
    restart: unless-stopped

  backend:
    container_name: backend
    image: camera-backend:latest
    privileged: true
    networks:
      - camera-net
    devices:
      - /dev/video0:/dev/video0
    depends_on:
      - mosquitto
      - mediamtx
    volumes:
      - /opt/camera-app/captures:/app/captures
      - /opt/camera-app/backend-certs:/app/backend-certs
    environment:
      MQTT_BROKER_HOST: "camera-mosquitto"
      MQTT_BROKER_PORT: "8883"
      MEDIA_MTX_HOST: "camera-mediamtx:8554"
    restart: unless-stopped
